name: blocky_blast
description: Blocky Blast Puzzle Game - HTML to Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
